version: "3"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "3001:8000"
  frontend:
    build: ./frontend/FastDrive
    ports:
      - "8081:80"
